#!/usr/bin/env just --justfile

all:
  just day01

run-example $SOLVER $INPUT_FILE_PATH $EXPECTED_OUTPUT:
  python app.py $SOLVER $INPUT_FILE_PATH --expected-output $EXPECTED_OUTPUT && echo "> $SOLVER -> Example OK"

run $SOLVER $INPUT_FILE_PATH:
  echo "> $SOLVER -> `python app.py $SOLVER $INPUT_FILE_PATH`"

day01:
  just day01-part1
  just day01-part2

day01-part1 $SOLVER="day01.part1" $EXAMPLE_FILE_PATH="../resources/day01/example-1.txt" $EXPECTED_OUTPUT="142" $INPUT_FILE_PATH="../resources/day01/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day01-part2 $SOLVER="day01.part2" $EXAMPLE_FILE_PATH="../resources/day01/example-2.txt" $EXPECTED_OUTPUT="281" $INPUT_FILE_PATH="../resources/day01/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day02-part1 $SOLVER="day02.part1" $EXAMPLE_FILE_PATH="../resources/day02/example.txt" $EXPECTED_OUTPUT="8" $INPUT_FILE_PATH="../resources/day02/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day02-part2 $SOLVER="day02.part2" $EXAMPLE_FILE_PATH="../resources/day02/example.txt" $EXPECTED_OUTPUT="2286" $INPUT_FILE_PATH="../resources/day02/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day03-part1 $SOLVER="day03.part1" $EXAMPLE_FILE_PATH="../resources/day03/example.txt" $EXPECTED_OUTPUT="4361" $INPUT_FILE_PATH="../resources/day03/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day03-part2 $SOLVER="day03.part2" $EXAMPLE_FILE_PATH="../resources/day03/example.txt" $EXPECTED_OUTPUT="467835" $INPUT_FILE_PATH="../resources/day03/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day04-part1 $SOLVER="day04.part1" $EXAMPLE_FILE_PATH="../resources/day04/example.txt" $EXPECTED_OUTPUT="13" $INPUT_FILE_PATH="../resources/day04/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day04-part2 $SOLVER="day04.part2" $EXAMPLE_FILE_PATH="../resources/day04/example.txt" $EXPECTED_OUTPUT="30" $INPUT_FILE_PATH="../resources/day04/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day05-part1 $SOLVER="day05.part1" $EXAMPLE_FILE_PATH="../resources/day05/example.txt" $EXPECTED_OUTPUT="35" $INPUT_FILE_PATH="../resources/day05/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day05-part2 $SOLVER="day05.part2" $EXAMPLE_FILE_PATH="../resources/day05/example.txt" $EXPECTED_OUTPUT="46" $INPUT_FILE_PATH="../resources/day05/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day06-part1 $SOLVER="day06.part1" $EXAMPLE_FILE_PATH="../resources/day06/example.txt" $EXPECTED_OUTPUT="288" $INPUT_FILE_PATH="../resources/day06/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day06-part2 $SOLVER="day06.part2" $EXAMPLE_FILE_PATH="../resources/day06/example.txt" $EXPECTED_OUTPUT="71503" $INPUT_FILE_PATH="../resources/day06/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day07-part1 $SOLVER="day07.part1" $EXAMPLE_FILE_PATH="../resources/day07/example.txt" $EXPECTED_OUTPUT="6440" $INPUT_FILE_PATH="../resources/day07/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day07-part2 $SOLVER="day07.part2" $EXAMPLE_FILE_PATH="../resources/day07/example.txt" $EXPECTED_OUTPUT="5905" $INPUT_FILE_PATH="../resources/day07/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day08-part1 $SOLVER="day08.part1" $EXAMPLE_1_FILE_PATH="../resources/day08/example-1.txt" $EXAMPLE_2_FILE_PATH="../resources/day08/example-2.txt" $EXPECTED_OUTPUT_1="2" $EXPECTED_OUTPUT_2="6" $INPUT_FILE_PATH="../resources/day08/input.txt":
  just run-example $SOLVER $EXAMPLE_1_FILE_PATH $EXPECTED_OUTPUT_1
  just run-example $SOLVER $EXAMPLE_2_FILE_PATH $EXPECTED_OUTPUT_2
  just run $SOLVER $INPUT_FILE_PATH

day08-part2 $SOLVER="day08.part2" $EXAMPLE_FILE_PATH="../resources/day08/example-3.txt" $EXPECTED_OUTPUT="6" $INPUT_FILE_PATH="../resources/day08/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day09-part1 $SOLVER="day09.part1" $EXAMPLE_FILE_PATH="../resources/day09/example.txt" $EXPECTED_OUTPUT="114" $INPUT_FILE_PATH="../resources/day09/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day09-part2 $SOLVER="day09.part2" $EXAMPLE_FILE_PATH="../resources/day09/example.txt" $EXPECTED_OUTPUT="2" $INPUT_FILE_PATH="../resources/day09/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day10-part1 $SOLVER="day10.part1" $EXAMPLE_1_FILE_PATH="../resources/day10/example-1.txt" $EXAMPLE_2_FILE_PATH="../resources/day10/example-2.txt" $EXPECTED_OUTPUT_1="4" $EXPECTED_OUTPUT_2="8" $INPUT_FILE_PATH="../resources/day10/input.txt":
  just run-example $SOLVER $EXAMPLE_1_FILE_PATH $EXPECTED_OUTPUT_1
  just run-example $SOLVER $EXAMPLE_2_FILE_PATH $EXPECTED_OUTPUT_2
  just run $SOLVER $INPUT_FILE_PATH

