#!/usr/bin/env just --justfile

all:
  just day01

run-example $SOLVER $INPUT_FILE_PATH $EXPECTED_OUTPUT:
  python app.py $SOLVER $INPUT_FILE_PATH --expected-output $EXPECTED_OUTPUT && echo "> $SOLVER -> Example OK"

run $SOLVER $INPUT_FILE_PATH:
  echo "> $SOLVER -> `python app.py $SOLVER $INPUT_FILE_PATH`"

day01:
  just day01-part1
  just day01-part2

day01-part1 $SOLVER="day01.part1" $EXAMPLE_FILE_PATH="../resources/day01/example-1.txt" $EXPECTED_OUTPUT="142" $INPUT_FILE_PATH="../resources/day01/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day01-part2 $SOLVER="day01.part2" $EXAMPLE_FILE_PATH="../resources/day01/example-2.txt" $EXPECTED_OUTPUT="281" $INPUT_FILE_PATH="../resources/day01/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day02-part1 $SOLVER="day02.part1" $EXAMPLE_FILE_PATH="../resources/day02/example.txt" $EXPECTED_OUTPUT="8" $INPUT_FILE_PATH="../resources/day02/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day02-part2 $SOLVER="day02.part2" $EXAMPLE_FILE_PATH="../resources/day02/example.txt" $EXPECTED_OUTPUT="2286" $INPUT_FILE_PATH="../resources/day02/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day03-part1 $SOLVER="day03.part1" $EXAMPLE_FILE_PATH="../resources/day03/example.txt" $EXPECTED_OUTPUT="4361" $INPUT_FILE_PATH="../resources/day03/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day03-part2 $SOLVER="day03.part2" $EXAMPLE_FILE_PATH="../resources/day03/example.txt" $EXPECTED_OUTPUT="467835" $INPUT_FILE_PATH="../resources/day03/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day04-part1 $SOLVER="day04.part1" $EXAMPLE_FILE_PATH="../resources/day04/example.txt" $EXPECTED_OUTPUT="13" $INPUT_FILE_PATH="../resources/day04/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day04-part2 $SOLVER="day04.part2" $EXAMPLE_FILE_PATH="../resources/day04/example.txt" $EXPECTED_OUTPUT="30" $INPUT_FILE_PATH="../resources/day04/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH

day05-part1 $SOLVER="day05.part1" $EXAMPLE_FILE_PATH="../resources/day05/example.txt" $EXPECTED_OUTPUT="35" $INPUT_FILE_PATH="../resources/day05/input.txt":
  just run-example $SOLVER $EXAMPLE_FILE_PATH $EXPECTED_OUTPUT
  just run $SOLVER $INPUT_FILE_PATH
